import fs from 'node:fs';
import path from 'node:path';

// Shared engine for every triage artifact. Confirmed bugs (BUG/) and
// flag-for-review findings (FLAGGED/) produce the identical folder layout and
// differ only in the markdown body, its filename, and the severity.json shape —
// which the caller supplies. Keeping this here is the single source of truth for
// "what a triage artifact folder contains", so the two report kinds cannot drift.

// Folder name is `<root>/<safe-iso>__seed<n>__<severity>`. Differs across kinds
// only by `root`; the timestamp sanitising and naming scheme are identical.
export function buildReportFolderName({ ts, seed, severity, root }) {
  const safeTs = ts.replace(/:/g, '-').replace(/\..+Z$/, 'Z');
  return path.join(root, `${safeTs}__seed${seed}__${severity}`);
}

// Numbered "1. summary" list of the action/navigate breadcrumbs.
export function renderStepLines(breadcrumbs) {
  return breadcrumbs
    .filter((b) => b.type === 'action' || b.type === 'navigate')
    .map((b, i) => `${i + 1}. ${b.summary}`)
    .join('\n');
}

// "## Evidence" block as a single string, or '' when there is no raw evidence.
export function renderEvidenceBlock(evidence = []) {
  if (!evidence.length) return '';
  return [
    '## Evidence (raw page-level signals)',
    '',
    ...evidence.map((e) => `- **${e.signal}** — ${e.detail}`),
    '',
  ].join('\n');
}

// "## How to reproduce" + artifact-pointer footer. Returned as discrete lines so
// the caller can spread them into its own array before `.filter(Boolean).join`,
// preserving the existing blank-line handling exactly.
export function reproSectionLines(folderRel) {
  return [
    '## How to reproduce',
    '',
    '```',
    `node ${folderRel.replace(/\\/g, '/')}/repro.js`,
    '```',
    '',
    'See `breadcrumbs.jsonl` for the full event log, `trace.jsonl` for OTel spans, ' +
      'and `steps/<n>.png` (in the run-id folder) for the per-step screenshot timeline.',
  ];
}

// The standalone repro.js that reruns the same seed.
export function renderRepro({ seed, pageUrl, configPath }) {
  return `// Auto-generated by heuristic-monkey triage. Reruns the same seed.
import { spawnSync } from 'node:child_process';
import path from 'node:path';
import url from 'node:url';

const here = path.dirname(url.fileURLToPath(import.meta.url));
const root = path.resolve(here, '..', '..');

const env = { ...process.env, HEURISTIC_SEED: '${seed}', HEURISTIC_TARGET_URL: '${pageUrl}' };
const result = spawnSync('node', [path.join(root, 'src/index.js'), '--config', '${configPath}'], {
  cwd: root,
  env,
  stdio: 'inherit',
});
process.exit(result.status ?? 1);
`;
}

// Generic artifact writer shared by confirmed bugs and flag-for-review findings.
// `renderMarkdown` receives the computed `folderRel` (so the body can embed its
// own path) and returns the report body; `markdownFile` and `severityPayload`
// carry the only other per-kind differences.
export async function writeReport({
  rootDir,
  root,
  seed,
  severity,
  pageUrl,
  breadcrumbs,
  screenshotBuffer = null,
  domHtml = '',
  tracePath = null,
  configPath = 'config.yaml',
  markdownFile,
  renderMarkdown,
  severityPayload,
}) {
  const ts = new Date().toISOString();
  const folderRel = buildReportFolderName({ ts, seed, severity, root });
  const folder = path.resolve(rootDir, folderRel);
  fs.mkdirSync(folder, { recursive: true });

  if (screenshotBuffer) {
    fs.writeFileSync(path.join(folder, 'screenshot.png'), screenshotBuffer);
  }
  if (domHtml) {
    fs.writeFileSync(path.join(folder, 'dom.html'), domHtml);
  }
  fs.writeFileSync(
    path.join(folder, 'breadcrumbs.jsonl'),
    breadcrumbs.map((b) => JSON.stringify(b)).join('\n'),
  );
  if (tracePath) {
    const resolvedTrace = path.resolve(rootDir, tracePath);
    if (fs.existsSync(resolvedTrace)) {
      fs.copyFileSync(resolvedTrace, path.join(folder, 'trace.jsonl'));
    }
  }

  fs.writeFileSync(path.join(folder, markdownFile), renderMarkdown(folderRel));
  fs.writeFileSync(path.join(folder, 'repro.js'), renderRepro({ seed, pageUrl, configPath }));
  fs.writeFileSync(path.join(folder, 'severity.json'), JSON.stringify(severityPayload, null, 2));

  return { folder, folderRel };
}
