import fs from 'node:fs';
import path from 'node:path';

// OWASP/CWE references per signal for the "What to fix" section.
const SIGNAL_REFS = {
  HTTP_500:                'https://owasp.org/www-community/vulnerabilities/Improper_Error_Handling',
  PAGEERROR:               'https://cwe.mitre.org/data/definitions/390.html',
  ASSET_4XX:               null,
  DOM_FROZEN:              null,
  MISSING_SECURITY_HEADERS:'https://owasp.org/www-project-secure-headers/',
  INSECURE_COOKIES:        'https://owasp.org/www-community/controls/SecureCookieAttribute',
  INFO_DISCLOSURE:         'https://cwe.mitre.org/data/definitions/209.html',
  CROSS_LAYER:             'https://cwe.mitre.org/data/definitions/1021.html',
  CROSS_ACCOUNT_LEAK:      'https://owasp.org/API-Security/editions/2023/en/0xa1-broken-object-level-authorization/',
  AUTHZ_UNCERTAIN:         'https://owasp.org/API-Security/editions/2023/en/0xa1-broken-object-level-authorization/',
  EXPOSED_BUNDLE_SECRET:   'https://cwe.mitre.org/data/definitions/312.html',
};

const WHAT_TO_FIX = {
  HTTP_500:                'Investigate server error handlers; ensure no uncaught exception returns a 5xx to the client.',
  HTTP_503_504:            'Check service availability and rate-limit handling in backend infrastructure.',
  PAGEERROR:               'Audit unhandled promise rejections and try/catch gaps in frontend JS.',
  ASSET_4XX:               'Fix broken asset references; ensure uploaded/referenced files are publicly accessible.',
  DOM_FROZEN:              'Check for infinite loading states or blank-screen regressions in the SPA.',
  MISSING_SECURITY_HEADERS:'Add X-Frame-Options, Content-Security-Policy, and HSTS via your host or reverse proxy.',
  INSECURE_COOKIES:        'Set HttpOnly and Secure flags on all auth cookies.',
  INFO_DISCLOSURE:         'Strip stack traces and DB error details from production HTTP responses.',
  CROSS_LAYER:             'Verify that delete/write operations are reflected in subsequent GET responses.',
  CROSS_ACCOUNT_LEAK:      'Audit Row Level Security policies; ensure each resource is scoped to its owner.',
  AUTHZ_UNCERTAIN:         'Review RLS policies for the flagged endpoint — unauthenticated read may be returning owned data.',
  EXPOSED_BUNDLE_SECRET:   'Rotate any exposed secret keys; audit environment variable handling in your build pipeline.',
};

function formatDuration(ms) {
  return ms < 1000 ? `${ms}ms` : `${(ms / 1000).toFixed(1)}s`;
}

function truncateUrl(url) {
  return url.length > 60 ? url.slice(0, 57) + '...' : url;
}

function findingTableRow(i, f) {
  const artifact = (f.folderRel ?? '').replace(/\\/g, '/');
  return `| ${i + 1} | ${f.signal ?? '—'} | ${f.severity ?? '—'} | ${truncateUrl(f.pageUrl ?? '')} | ${artifact} |`;
}

function renderMarkdown({ runId, seed, targetUrl, mode, date, durationMs, bugs, flagged }) {
  const lines = [
    '# Stochastic Monkey — Bug Report',
    '',
    `**Target:** ${targetUrl}`,
    `**Run ID:** ${runId}  **Seed:** ${seed}  **Mode:** ${mode}`,
    `**Date:** ${date}  **Duration:** ${formatDuration(durationMs)}`,
    '',
    `## Findings (${bugs.length} bug${bugs.length !== 1 ? 's' : ''}, ${flagged.length} flagged)`,
    '',
    '### Bugs (auto-confirmed)',
    '',
  ];

  if (bugs.length) {
    lines.push('| # | Signal | Severity | URL | Artifact |');
    lines.push('|---|--------|----------|-----|----------|');
    bugs.forEach((b, i) => lines.push(findingTableRow(i, b)));
  } else {
    lines.push('No confirmed bugs found this run.');
  }

  lines.push('', '### Flagged (needs review)', '');

  if (flagged.length) {
    lines.push('| # | Signal | Severity | URL | Artifact |');
    lines.push('|---|--------|----------|-----|----------|');
    flagged.forEach((f, i) => lines.push(findingTableRow(i, f)));
  } else {
    lines.push('No flagged findings this run.');
  }

  const allSignals = [...new Set([...bugs, ...flagged].map((f) => f.signal).filter(Boolean))];
  if (allSignals.length) {
    lines.push('', '## What to fix', '');
    for (const sig of allSignals) {
      const advice = WHAT_TO_FIX[sig] ?? `Review occurrences of ${sig} in the artifact folders above.`;
      const ref = SIGNAL_REFS[sig];
      lines.push(`- **${sig}:** ${advice}${ref ? ` ([reference](${ref}))` : ''}`);
    }
  }

  lines.push(
    '',
    '---',
    '*Generated by [Stochastic Monkey](https://github.com/AngelGalindo7/Stochastic-Monkey)*',
  );

  return lines.join('\n');
}

export function writeSummaryReport({ rootDir, runId, seed, targetUrl, mode, bugs, flagged, durationMs }) {
  const date = new Date().toISOString();
  const summaryDir = path.resolve(rootDir, 'BUG', runId, 'summary');
  fs.mkdirSync(summaryDir, { recursive: true });

  fs.writeFileSync(
    path.join(summaryDir, 'report.md'),
    renderMarkdown({ runId, seed, targetUrl, mode, date, durationMs, bugs, flagged }),
  );

  fs.writeFileSync(
    path.join(summaryDir, 'report.json'),
    JSON.stringify({ runId, seed, targetUrl, mode, date, durationMs, bugs, flagged }, null, 2),
  );

  return path.join('BUG', runId, 'summary', 'report.md');
}
