import fs from 'node:fs';
import path from 'node:path';

export function buildBugFolderName({ ts, seed, severity, root = 'BUG' }) {
  const safeTs = ts.replace(/:/g, '-').replace(/\..+Z$/, 'Z');
  return path.join(root, `${safeTs}__seed${seed}__${severity}`);
}

export async function writeBugReport({
  rootDir,
  bugRoot = 'BUG',
  seed,
  severity,
  signal,
  pageUrl,
  breadcrumbs,
  screenshotBuffer = null,
  domHtml = '',
  surpriseScore = null,
  prediction = null,
  evidence = [],
  tracePath = null,
  stepsDirRel = null,
  config,
}) {
  const ts = new Date().toISOString();
  const folderRel = buildBugFolderName({ ts, seed, severity, root: bugRoot });
  const folder = path.resolve(rootDir, folderRel);
  fs.mkdirSync(folder, { recursive: true });

  if (screenshotBuffer) {
    fs.writeFileSync(path.join(folder, 'screenshot.png'), screenshotBuffer);
  }
  if (domHtml) {
    fs.writeFileSync(path.join(folder, 'dom.html'), domHtml);
  }
  fs.writeFileSync(
    path.join(folder, 'breadcrumbs.jsonl'),
    breadcrumbs.map((b) => JSON.stringify(b)).join('\n'),
  );
  if (tracePath) {
    const resolvedTrace = path.resolve(rootDir, tracePath);
    if (fs.existsSync(resolvedTrace)) {
      fs.copyFileSync(resolvedTrace, path.join(folder, 'trace.jsonl'));
    }
  }

  const bugMd = renderBugMd({
    pageUrl,
    severity,
    signal,
    seed,
    breadcrumbs,
    prediction,
    surpriseScore,
    folderRel,
    stepsDirRel,
    evidence,
  });
  fs.writeFileSync(path.join(folder, 'bug.md'), bugMd);

  const repro = renderRepro({ seed, pageUrl, configPath: 'config.yaml' });
  fs.writeFileSync(path.join(folder, 'repro.js'), repro);

  fs.writeFileSync(
    path.join(folder, 'severity.json'),
    JSON.stringify({ severity, signal, surpriseScore }, null, 2),
  );

  return { folder, folderRel };
}

function renderBugMd({
  pageUrl,
  severity,
  signal,
  seed,
  breadcrumbs,
  prediction,
  surpriseScore,
  folderRel,
  stepsDirRel,
  evidence = [],
}) {
  const stepLines = breadcrumbs
    .filter((b) => b.type === 'action' || b.type === 'navigate')
    .map((b, i) => `${i + 1}. ${b.summary}`)
    .join('\n');

  const evidenceBlock = evidence.length
    ? [
        '## Evidence (raw page-level signals)',
        '',
        ...evidence.map((e) => `- **${e.signal}** — ${e.detail}`),
        '',
      ].join('\n')
    : '';

  return [
    `# Bug Report — ${severity.toUpperCase()}`,
    '',
    `**URL:** ${pageUrl}`,
    `**Seed:** ${seed}`,
    `**Signal:** ${signal}`,
    surpriseScore !== null ? `**Surprise score:** ${surpriseScore.toFixed(2)}` : '',
    `**Folder:** ${folderRel}`,
    stepsDirRel ? `**Step screenshots:** ${stepsDirRel.replace(/\\/g, '/')}/` : '',
    '',
    evidenceBlock,
    '## Steps the agent took before failure',
    '',
    stepLines || '(no action breadcrumbs recorded)',
    '',
    prediction ? `## Predicted outcome\n\n> ${prediction}\n` : '',
    '## How to reproduce',
    '',
    '```',
    `node ${folderRel.replace(/\\/g, '/')}/repro.js`,
    '```',
    '',
    'See `breadcrumbs.jsonl` for the full event log, `trace.jsonl` for OTel spans, ' +
      'and `steps/<n>.png` (in the run-id folder) for the per-step screenshot timeline.',
  ]
    .filter(Boolean)
    .join('\n');
}

function renderRepro({ seed, pageUrl, configPath }) {
  return `// Auto-generated by heuristic-monkey triage. Reruns the same seed.
import { spawnSync } from 'node:child_process';
import path from 'node:path';
import url from 'node:url';

const here = path.dirname(url.fileURLToPath(import.meta.url));
const root = path.resolve(here, '..', '..');

const env = { ...process.env, HEURISTIC_SEED: '${seed}', HEURISTIC_TARGET_URL: '${pageUrl}' };
const result = spawnSync('node', [path.join(root, 'src/index.js'), '--config', '${configPath}'], {
  cwd: root,
  env,
  stdio: 'inherit',
});
process.exit(result.status ?? 1);
`;
}
