// Auto-generated by heuristic-monkey triage. Reruns the same seed.
import { spawnSync } from 'node:child_process';
import path from 'node:path';
import url from 'node:url';

const here = path.dirname(url.fileURLToPath(import.meta.url));
const root = path.resolve(here, '..', '..');

const env = { ...process.env, HEURISTIC_SEED: '3003', HEURISTIC_TARGET_URL: 'https://the-internet.herokuapp.com/status_codes/500' };
const result = spawnSync('node', [path.join(root, 'src/index.js'), '--config', 'config.yaml'], {
  cwd: root,
  env,
  stdio: 'inherit',
});
process.exit(result.status ?? 1);
